default:
  rhino_log_level: !expr Sys.getenv("RHINO_LOG_LEVEL", "INFO")
  rhino_log_file: !expr Sys.getenv("RHINO_LOG_FILE", NA)
  players: "app/data/players.rds"
  squads: "app/data/squads.rds"
dev:
  players: "app/data/players_dev.rds"
